repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: ruff check
      language: system
      types: [python]
      args: [--fix]
- repo: local
  hooks:
    - id: flake8
      name: flake8
      description: Run flake8
      entry: flake8
      language: system
      types: [ python ]
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true
        args: [--namespace-packages,
               --explicit-package-bases,
               --check-untyped-defs,
               --disable-error-code=import-untyped]
