[tool.ruff]
line-length = 120

[tool.ruff.lint]
fixable = ["I"]  # Allow auto-fix for imports only
select = ["E", "F", "I", "TCH"]  # Enable error codes

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
module = "torchvision.*"
ignore_missing_imports = true  # Ignore missing type hints for torchvision
